# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hdus/dev/qgis/qgis-cloud-plugin/qgiscloud/ui_qgiscloudplugin.ui'
#
# Created: Wed Apr 24 08:35:39 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QgisCloudPlugin(object):
    def setupUi(self, QgisCloudPlugin):
        QgisCloudPlugin.setObjectName(_fromUtf8("QgisCloudPlugin"))
        QgisCloudPlugin.resize(429, 602)
        QgisCloudPlugin.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.services = QtGui.QWidget()
        self.services.setObjectName(_fromUtf8("services"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.services)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.logo = QtGui.QLabel(self.services)
        self.logo.setAutoFillBackground(False)
        self.logo.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/qgiscloud/logo.png")))
        self.logo.setScaledContents(False)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName(_fromUtf8("logo"))
        self.verticalLayout_7.addWidget(self.logo)
        self.btnPublishMap = QtGui.QPushButton(self.services)
        self.btnPublishMap.setObjectName(_fromUtf8("btnPublishMap"))
        self.verticalLayout_7.addWidget(self.btnPublishMap)
        self.serviceLinks = QtGui.QStackedWidget(self.services)
        self.serviceLinks.setMaximumSize(QtCore.QSize(16777215, 140))
        self.serviceLinks.setObjectName(_fromUtf8("serviceLinks"))
        self.pageStart = QtGui.QWidget()
        self.pageStart.setObjectName(_fromUtf8("pageStart"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.pageStart)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_7 = QtGui.QLabel(self.pageStart)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setOpenExternalLinks(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_9.addWidget(self.label_7)
        self.label_6 = QtGui.QLabel(self.pageStart)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_9.addWidget(self.label_6)
        self.label_9 = QtGui.QLabel(self.pageStart)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setOpenExternalLinks(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_9.addWidget(self.label_9)
        spacerItem = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.serviceLinks.addWidget(self.pageStart)
        self.pageVersions = QtGui.QWidget()
        self.pageVersions.setObjectName(_fromUtf8("pageVersions"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pageVersions)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_13 = QtGui.QLabel(self.pageVersions)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_3.addWidget(self.label_13)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblVersionQGIS = QtGui.QLabel(self.pageVersions)
        self.lblVersionQGIS.setText(_fromUtf8(""))
        self.lblVersionQGIS.setObjectName(_fromUtf8("lblVersionQGIS"))
        self.gridLayout_3.addWidget(self.lblVersionQGIS, 3, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.pageVersions)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 3, 1, 1, 1)
        self.lblVersionPlugin = QtGui.QLabel(self.pageVersions)
        self.lblVersionPlugin.setText(_fromUtf8(""))
        self.lblVersionPlugin.setObjectName(_fromUtf8("lblVersionPlugin"))
        self.gridLayout_3.addWidget(self.lblVersionPlugin, 4, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.pageVersions)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 5, 1, 1, 1)
        self.lblVersionPython = QtGui.QLabel(self.pageVersions)
        self.lblVersionPython.setText(_fromUtf8(""))
        self.lblVersionPython.setObjectName(_fromUtf8("lblVersionPython"))
        self.gridLayout_3.addWidget(self.lblVersionPython, 6, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.pageVersions)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 4, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.pageVersions)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 6, 1, 1, 1)
        self.lblVersionOGR = QtGui.QLabel(self.pageVersions)
        self.lblVersionOGR.setText(_fromUtf8(""))
        self.lblVersionOGR.setObjectName(_fromUtf8("lblVersionOGR"))
        self.gridLayout_3.addWidget(self.lblVersionOGR, 5, 2, 1, 1)
        self.lblVersionOS = QtGui.QLabel(self.pageVersions)
        self.lblVersionOS.setText(_fromUtf8(""))
        self.lblVersionOS.setObjectName(_fromUtf8("lblVersionOS"))
        self.gridLayout_3.addWidget(self.lblVersionOS, 7, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.pageVersions)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 7, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.serviceLinks.addWidget(self.pageVersions)
        self.pageLinks = QtGui.QWidget()
        self.pageLinks.setObjectName(_fromUtf8("pageLinks"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pageLinks)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.pageLinks)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lblWebmap = QtGui.QLabel(self.pageLinks)
        self.lblWebmap.setOpenExternalLinks(True)
        self.lblWebmap.setObjectName(_fromUtf8("lblWebmap"))
        self.gridLayout.addWidget(self.lblWebmap, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.pageLinks)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lblMobileMap = QtGui.QLabel(self.pageLinks)
        self.lblMobileMap.setEnabled(True)
        self.lblMobileMap.setOpenExternalLinks(True)
        self.lblMobileMap.setObjectName(_fromUtf8("lblMobileMap"))
        self.gridLayout.addWidget(self.lblMobileMap, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.pageLinks)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.lblWMS = QtGui.QLabel(self.pageLinks)
        self.lblWMS.setOpenExternalLinks(True)
        self.lblWMS.setObjectName(_fromUtf8("lblWMS"))
        self.gridLayout.addWidget(self.lblWMS, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.pageLinks)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lblMaps = QtGui.QLabel(self.pageLinks)
        self.lblMaps.setOpenExternalLinks(True)
        self.lblMaps.setObjectName(_fromUtf8("lblMaps"))
        self.gridLayout.addWidget(self.lblMaps, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.pageLinks)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.lblMobileMap_2 = QtGui.QLabel(self.pageLinks)
        self.lblMobileMap_2.setEnabled(True)
        self.lblMobileMap_2.setOpenExternalLinks(True)
        self.lblMobileMap_2.setObjectName(_fromUtf8("lblMobileMap_2"))
        self.gridLayout.addWidget(self.lblMobileMap_2, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.serviceLinks.addWidget(self.pageLinks)
        self.verticalLayout_7.addWidget(self.serviceLinks)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.tabWidget.addTab(self.services, _fromUtf8(""))
        self.upload = QtGui.QWidget()
        self.upload.setObjectName(_fromUtf8("upload"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.upload)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.upload)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.cbUploadDatabase = QtGui.QComboBox(self.upload)
        self.cbUploadDatabase.setObjectName(_fromUtf8("cbUploadDatabase"))
        self.horizontalLayout_3.addWidget(self.cbUploadDatabase)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.tblLocalLayers = QtGui.QTableWidget(self.upload)
        self.tblLocalLayers.setObjectName(_fromUtf8("tblLocalLayers"))
        self.tblLocalLayers.setColumnCount(0)
        self.tblLocalLayers.setRowCount(0)
        self.tblLocalLayers.verticalHeader().setVisible(False)
        self.verticalLayout_10.addWidget(self.tblLocalLayers)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.btnRefreshLocalLayers = QtGui.QPushButton(self.upload)
        self.btnRefreshLocalLayers.setObjectName(_fromUtf8("btnRefreshLocalLayers"))
        self.horizontalLayout_7.addWidget(self.btnRefreshLocalLayers)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.cbReplaceLocalLayers = QtGui.QCheckBox(self.upload)
        self.cbReplaceLocalLayers.setChecked(True)
        self.cbReplaceLocalLayers.setObjectName(_fromUtf8("cbReplaceLocalLayers"))
        self.verticalLayout_10.addWidget(self.cbReplaceLocalLayers)
        self.btnUploadData = QtGui.QPushButton(self.upload)
        self.btnUploadData.setObjectName(_fromUtf8("btnUploadData"))
        self.verticalLayout_10.addWidget(self.btnUploadData)
        self.uploadProgressBar = QtGui.QProgressBar(self.upload)
        self.uploadProgressBar.setProperty("value", 24)
        self.uploadProgressBar.setObjectName(_fromUtf8("uploadProgressBar"))
        self.verticalLayout_10.addWidget(self.uploadProgressBar)
        self.btnPublishMapUpload = QtGui.QPushButton(self.upload)
        self.btnPublishMapUpload.setObjectName(_fromUtf8("btnPublishMapUpload"))
        self.verticalLayout_10.addWidget(self.btnPublishMapUpload)
        self.tabWidget.addTab(self.upload, _fromUtf8(""))
        self.account = QtGui.QWidget()
        self.account.setObjectName(_fromUtf8("account"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.account)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.account)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.editServer = QtGui.QLineEdit(self.account)
        self.editServer.setEnabled(False)
        self.editServer.setObjectName(_fromUtf8("editServer"))
        self.horizontalLayout_4.addWidget(self.editServer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnLogin = QtGui.QPushButton(self.account)
        self.btnLogin.setObjectName(_fromUtf8("btnLogin"))
        self.horizontalLayout_5.addWidget(self.btnLogin)
        self.lblSignup = QtGui.QLabel(self.account)
        self.lblSignup.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSignup.setOpenExternalLinks(True)
        self.lblSignup.setObjectName(_fromUtf8("lblSignup"))
        self.horizontalLayout_5.addWidget(self.lblSignup)
        self.lblLoginStatus = QtGui.QLabel(self.account)
        self.lblLoginStatus.setObjectName(_fromUtf8("lblLoginStatus"))
        self.horizontalLayout_5.addWidget(self.lblLoginStatus)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.groupBox_3 = QtGui.QGroupBox(self.account)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabDatabases = QtGui.QListWidget(self.groupBox_3)
        self.tabDatabases.setObjectName(_fromUtf8("tabDatabases"))
        self.verticalLayout_4.addWidget(self.tabDatabases)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnDbRefresh = QtGui.QPushButton(self.groupBox_3)
        self.btnDbRefresh.setObjectName(_fromUtf8("btnDbRefresh"))
        self.horizontalLayout.addWidget(self.btnDbRefresh)
        spacerItem5 = QtGui.QSpacerItem(37, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnDbCreate = QtGui.QPushButton(self.groupBox_3)
        self.btnDbCreate.setObjectName(_fromUtf8("btnDbCreate"))
        self.horizontalLayout_2.addWidget(self.btnDbCreate)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnDbDelete = QtGui.QPushButton(self.groupBox_3)
        self.btnDbDelete.setEnabled(False)
        self.btnDbDelete.setObjectName(_fromUtf8("btnDbDelete"))
        self.horizontalLayout_6.addWidget(self.btnDbDelete)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.account, _fromUtf8(""))
        self.about = QtGui.QWidget()
        self.about.setObjectName(_fromUtf8("about"))
        self.gridLayout_4 = QtGui.QGridLayout(self.about)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.aboutText = QtGui.QTextEdit(self.about)
        self.aboutText.setObjectName(_fromUtf8("aboutText"))
        self.gridLayout_4.addWidget(self.aboutText, 0, 0, 1, 1)
        self.tabWidget.addTab(self.about, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        QgisCloudPlugin.setWidget(self.dockWidgetContents)
        self.label_2.setBuddy(self.editServer)

        self.retranslateUi(QgisCloudPlugin)
        self.tabWidget.setCurrentIndex(0)
        self.serviceLinks.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QgisCloudPlugin)

    def retranslateUi(self, QgisCloudPlugin):
        QgisCloudPlugin.setWindowTitle(QtGui.QApplication.translate("QgisCloudPlugin", "QGIS Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPublishMap.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Publish Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("QgisCloudPlugin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">QGIS Cloud Hosting</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://qgiscloud.com/\"><span style=\" text-decoration: underline; color:#0057ae;\">qgiscloud.com</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Publish your own maps directly from the desktop!\n"
"\n"
"It\'s free to get started and sign up is instant. Publish your first map within minutes.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("QgisCloudPlugin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://qgiscloud.com/account/sign_up\"><span style=\" text-decoration: underline; color:#0057ae;\">Signup</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Versions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("QgisCloudPlugin", "QGIS:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("QgisCloudPlugin", "OGR/GDAL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Plugin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Python:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("QgisCloudPlugin", "OS:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Webmap", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWebmap.setText(QtGui.QApplication.translate("QgisCloudPlugin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://qgiscloud.com/user/map\"><span style=\" font-family:\'Ubuntu\'; text-decoration: underline; color:#0057ae;\">http://qgiscloud.com/user/map</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Mobile map", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMobileMap.setText(QtGui.QApplication.translate("QgisCloudPlugin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://m.qgiscloud.com/user/map\"><span style=\" font-family:\'Ubuntu\'; text-decoration: underline; color:#0057ae;\">http://m.qgiscloud.com/user/map</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Public WMS", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWMS.setText(QtGui.QApplication.translate("QgisCloudPlugin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://wms.qgiscloud.com/user/map\"><span style=\" font-family:\'Ubuntu\'; text-decoration: underline; color:#0057ae;\">http://wms.qgiscloud.com/user/map</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Map Admin", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMaps.setText(QtGui.QApplication.translate("QgisCloudPlugin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://qgiscloud.com/maps\"><span style=\" font-family:\'Ubuntu\'; text-decoration: underline; color:#0057ae;\">http://qgiscloud.com/maps</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Support", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMobileMap_2.setText(QtGui.QApplication.translate("QgisCloudPlugin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"mailto:support@qgiscloud.com?subject=QGISCloud support\"><span style=\" font-family:\'Ubuntu\'; text-decoration: underline; color:#0057ae;\">support@qgiscloud.com</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.services), QtGui.QApplication.translate("QgisCloudPlugin", "Services", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefreshLocalLayers.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Refresh layers", None, QtGui.QApplication.UnicodeUTF8))
        self.cbReplaceLocalLayers.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Replace local layers in project", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUploadData.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Upload data", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPublishMapUpload.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Publish Map", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.upload), QtGui.QApplication.translate("QgisCloudPlugin", "Upload Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.editServer.setText(QtGui.QApplication.translate("QgisCloudPlugin", "https://api.qgiscloud.com", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogin.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSignup.setText(QtGui.QApplication.translate("QgisCloudPlugin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://qgiscloud.com/account/sign_up\"><span style=\" text-decoration: underline; color:#0057ae;\">Signup</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoginStatus.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Logged in as ...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("QgisCloudPlugin", "Databases", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDbRefresh.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDbCreate.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Create new database", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDbDelete.setText(QtGui.QApplication.translate("QgisCloudPlugin", "Delete database", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.account), QtGui.QApplication.translate("QgisCloudPlugin", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about), QtGui.QApplication.translate("QgisCloudPlugin", "About", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    QgisCloudPlugin = QtGui.QDockWidget()
    ui = Ui_QgisCloudPlugin()
    ui.setupUi(QgisCloudPlugin)
    QgisCloudPlugin.show()
    sys.exit(app.exec_())

